import type { Metadata } from 'next';
import '@/styles/globals.css';
import { Providers } from './providers';
import { UserProvider } from '@/context/userContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserProvider>
      <html lang='en'>
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    </UserProvider>
  );
}
